# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180517_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tema',
            field=models.CharField(default='nada', max_length=200),
        ),
    ]
